CHAR . CONSTANT DOT
CHAR * CONSTANT STAR

\ put a star if n is even, else a dot 
: DOT-OR-CHAR ( n -- c )
    1 AND IF DOT ELSE CHAR THEN ;
    
0 DOT-OR-CHAR EMIT CR
1 DOT-OR-CHAR EMIT CR
0 DOT-OR-CHAR EMIT CR

BYE
